### PR TITLE
:arrow_up: Update zetta-scientist

### PR DESCRIPTION
**Pull request by marvinroger**
Allow ES2015 plugins.

### CODE REVIEW

**Comment by AdamMagaluk** [comment]
zetta-scout also depends on zetta-scientist would need a PR there too to keep them at the same version. Maybe we should wait until i do a fix for #347

**Comment by marvinroger** [comment]
I see. You're right, this is an important concern.

**Comment by AdamMagaluk** [comment]
Also slight nit pick: What's with the emojis in the commits and PR titles? They get carried over to the home screen of zetta with each folder/file last commit.

**Comment by marvinroger** [comment]
This is intentional. It is a practice first introduced in the Atom IDE repo if I remember well (see https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages).

It allows you to quickly see what kind a commit is (dep update (:arrow_up:), bugfix (:bug:), feature (:sparkles:)).
You can "hide" this commit message by squashing the commits into one and by giving your own commit message (you can do that with the drop down next to the Merge button).

**Comment by AdamMagaluk** [comment]
Call me old but I'd prefer to keep Zetta and it's deps emoji free. Just use plain text in the commits to signify commit types. eg. `BUG: Fixed #123 for spdy event stream handling`

**Pull request closed without merging**
