### PR TITLE
Updates to query API.

### PR DESCRIPTION
**Pull request by mdobson**
Updates for #189

### CODE REVIEW

**Comment by AdamMagaluk** [comment]
The only issue i'm seeing is with the server="Detroit" query in the properties returned it has `{ name: "Detroit", ql: ... }`

vs when doing a query with server="*" it shows up as `{ server: "*", ql: ... }`

We can probably just do something like:

```js
body.properties.server = body.properties.name;
delete body.properties.name;
```

**Comment by mdobson** [comment]
Pish posh!

**Comment by AdamMagaluk** [comment]
Should the self link point back to the root of the api or /servers/Detroit when querying server="Detroit"? I'm thinking the former.

**Comment by AdamMagaluk** [comment]
+1 Merge when Travis goes green.

**Comment by kevinswiber** [comment]
I think it should point to the root.

On Fri, May 8, 2015 at 2:21 PM, Adam Magaluk <notifications@github.com>
wrote:

> Should the self link point back to the root of the api or /servers/Detroit
> when querying server="Detroit"? I'm thinking the former.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zettajs/zetta/pull/190#issuecomment-100319552>.
>



-- 
Kevin Swiber
Projects: https://github.com/kevinswiber
Twitter: @kevinswiber

**Pull request merged**
