### PR TITLE
Removed try/catch around callbacks

### PR DESCRIPTION
**Pull request by AdamMagaluk**
Still working on a way to test this.

### CODE REVIEW

**Comment by mdobson** [comment]
Was this the thing eating errors yesterday?

**Comment by AdamMagaluk** [comment]
Yeah, the registry.match was catching those errors.

**Comment by kevinswiber** [comment]
The try-catch was for query parse errors.  Maybe we can be smarter about that.

**Comment by kevinswiber** [comment]
Never mind.  I see what you did there.

**Comment by AdamMagaluk** [comment]
@kevinswiber Yep, it's still in there just wrapping the callback. I had to add an extra try/catch for match because of how find method worked on the session.

**Comment by kevinswiber** [comment]
Looks good.  Merge, pending the greening of Travis.

**Pull request merged**
