### PR TITLE
Support runtime updates of device properties via the API.

### PR DESCRIPTION
**Pull request by kevinswiber**
Stubbed out server update via API.  Implemented device update via API.

Not ready for merge.

### CODE REVIEW

**Comment by kevinswiber** [comment]
Device data saves seem to be working well.  However, this bug is getting in the way of a demo: https://github.com/zettajs/zetta-auto-scout/issues/6

**Comment by kevinswiber** [comment]
Removed server update stub.  We'll do that in a later PR.  More to discuss there.

Leaving AutoScout the way it is for now.  Will address this concern in a separate PR for zettajs/zetta-auto-scout and another PR for tests in zettajs/zetta.

@mdobson @AdamMagaluk Ready for review!

**Comment by mdobson** [comment]
Looks good to me. Any objections @AdamMagaluk ?

**Comment by kevinswiber** [comment]
We talked about denying monitored property updates and adding an event hook to notify interested parties of the change. Is that something you want to get in first? I'll leave it up to youse guys.

**Comment by mdobson** [comment]
Ah yes. Sorry. Must've forgot about that. Those things sound good to have in. I'd be okay holding off until that is the case.

**Comment by AdamMagaluk** [comment]
Yeah I say we try and get those two things in before we merge, I can look at implementing it today.

**Comment by mdobson** [comment]
I'm implementing the monitor guard currently. Pretty close to it. Did we talk about the structure of what the update notification would look like?

**Comment by AdamMagaluk** [comment]
Ok cool. No not in any detail.

We emit a message when a transition happens on the logs topic for the device. That looks like:

```
{
  "topic": "led/82e91539-1b32-4c82-8c40-1647f06fc52d/logs",
  "timestamp": 1437660657339,
  "transition": "turn-on",
  "input": [],
  "properties": {
    "led": 1,
    "id": "82e91539-1b32-4c82-8c40-1647f06fc52d",
    "name": 1,
    "type": "led",
    "state": "on"
  },
  "actions": [...]
}
```

Maybe the `transition` field has a special value for remote updates. Or a different field that represents a remote update. Then get rid of the `input` field.

**Comment by AdamMagaluk** [comment]
I'm thinking we come up with a reserved transition name for remote updates, than we can treat it like any other transition. If we use the `logs` topic on the device there are a number of places throughout the code that expect `transition` field is set on the message.

Some possible names `properties-update`, `zetta-properties-update`, `device-properties-update`

**Comment by mdobson** [comment]
So something like this?

```
{
  "topic": "led/82e91539-1b32-4c82-8c40-1647f06fc52d/logs",
  "timestamp": 1437660657339,
  "transition": "zetta-properties-update",
  "input": [],
  "properties": {
    "led": 1,
    "id": "82e91539-1b32-4c82-8c40-1647f06fc52d",
    "name": 1,
    "type": "led",
    "state": "on"
  },
  "actions": [...]
}
```

**Comment by AdamMagaluk** [comment]
Yeah

**Comment by mdobson** [comment]
Cool. I'll run with this.

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by mdobson** [comment]
Additions ready for inspection.

**Comment by AdamMagaluk** [comment]
Perfection.

**Pull request merged**
