### PR TITLE
Handle peer's spdy agent error event

### PR DESCRIPTION
**Pull request by AdamMagaluk**
See #137

### CODE REVIEW

**Comment by AdamMagaluk** [comment]
Not sure if there is a good way to properly test this. Any thoughts @mdobson

**Comment by mdobson** [comment]
You could emit the "error" event on this.agent I suppose.

**Comment by mdobson** [comment]
then check that the same error is emitted by the peer_socket object.

**Comment by mdobson** [comment]
#mergeit

**Pull request merged**
