### PR TITLE
Emit and Publish Peer Connection Errors

### PR DESCRIPTION
**Pull request by wooliet**
A zetta instance's `pubsub` can be used to react to peer client disconnect events. Currently, the _peer_client_ module will emit a "closed" event for **both** error and close events.

_peer_client_
```javascript
self.ws.on('error', function onError(err) {
   //...
  self.emit('closed');
});
```

The following zetta handle of "error" events (and it publish of a "disconnect" topic) will never be called.
```javascript
peerClient.on('error', function(error) {
  self.peerRegistry.get(peer.id, function(err, result) {
    result.status = 'failed';
    result.error = error;
    result.connectionId = peerClient.connectionId;
    self.peerRegistry.save(result);

    // peer-event
    self.pubsub.publish('_peer/disconnect', { peer: peerClient });
  });
});
```

This PR adds `emit('error', err)` to the _peer_client_ module, and updates the _zetta_ handler to publish a '_peer/error' topic with the `error` and `peerClient` objects. 

It is not expected to cause issues with current code because the "error" event handler was previously never called.

### CODE REVIEW

**Comment by AdamMagaluk** [comment]
Hi @wooliet, 

To start i'd be interested in why and what information you're currently lacking with zetta? Is it just the `error` message to see why it failed?

I have a concerns about adding another `_peer/<event>` type of event.

1. When the peer_client disconnects with an error the peer registry will be in an intermittent state. Since in zetta.js we're looking for both `closed` and `error` and updating the registry i'm not sure what will always end up in the registry in this case because we're emitting both the events. [Code Here](https://github.com/zettajs/zetta/blob/bcd2bc8c45a261dbaf4b3dd2ac3ee0ace15db0b4/zetta.js#L444-L466)

2. If we add the `_peer/error` event we may need to add it the events that are sent over the `/peer-management` websocket endpoint. Would it feel strange for a client to receive a disconnect and an error event? [Code Here](https://github.com/zettajs/zetta/blob/bcd2bc8c45a261dbaf4b3dd2ac3ee0ace15db0b4/lib/http_server.js#L127-L133)

3. Thinking about the other direction peers connecting to a cloud. Should the cloud zetta also emit a `_peer/error` event when the peer_socket emits an error? [Code Here](https://github.com/zettajs/zetta/blob/bcd2bc8c45a261dbaf4b3dd2ac3ee0ace15db0b4/lib/http_server.js#L117-L120)

I would like to propose an alternative approach. Have the peer_client emit only the `error` event when the underlying websocket emits `error`. In zetta.js still have it emit `_peer/disconnect` but with an additional error property on the object that's emitted. This will keep the peer-management api and our events the same but provide the additional info as well as address the issue that the peer_clients error event is never emitted and thus the registry never says the peer went into a failed state.

**Comment by wooliet** [comment]
@AdamMagaluk 

I have a zetta instance "linked" to another. When the main instance restarts and has a new location, I want to be sure and trigger a reconnect process for the original. When the instance tries to connect to a bad location, the ultimate error is "ECONNREFUSED". I wanted to handle that specific issue.

1. "Emitting both events": Are you sure you're emitting both? I am pretty certain that the peer client error handler is **never** called ([looking here](https://github.com/zettajs/zetta/blob/master/lib/peer_client.js#L140-L145)). I scanned a few unit tests but (to be honest) did not spend the time to create one that would confirm this behavior. If the peer registry state is working as expected now, it might be a side-effect of something else, and not because the error handler is executed. 

2. "Peer Management": Receiving two distinct events would not feel strange. But it also makes sense to indicate that the disconnect was triggered by an error by including an `error` with the event data.

3. "Peers to Cloud": Same as above.

"Alternative Approach": Your suggestion is the same as my first pass at this. But when I realized that the "error" event is never actually emitted by _peer_client_, it seemed cleaner to me to publish a unique topic as opposed adding additional data to existing topics.

**Comment by AdamMagaluk** [comment]
Regarding 1. Today we are only emitting `closed`. My proposal would be to have it emit _only_ `error` [here](https://github.com/zettajs/zetta/blob/master/lib/peer_client.js#L143). My concern was that in your PR we are now emitting both [here](https://github.com/wooliet/zetta/blob/b789ad16a65441ccd671d3f918e20442dec9cdcf/lib/peer_client.js#L143-L144) which would lead to both of the handlers in zetta.js to be called at the same time. [here](https://github.com/wooliet/zetta/blob/b789ad16a65441ccd671d3f918e20442dec9cdcf/zetta.js#L444-L466)

**Comment by AdamMagaluk** [comment]
@wooliet This is kinda what i'm thinking. https://github.com/zettajs/zetta/commit/6206dc5ab199e0b9b039e1deac3074ee2f88db99

**Comment by wooliet** [comment]
@AdamMagaluk Yeah, that looks right. I agree it'd be better to not emit both "closed" and "error".

I don't know the implications of adding the `error` data in _event_socket_.

**Comment by AdamMagaluk** [comment]
The small update i made in event_socket would allow ws clients subscribed to `/peer-management` to see if an error occurred on disconnect.  Because we can't send the entire peerClient down the websocket we override the actual data with peerClients.properties() but that doesn't included the error parameter.

**Comment by AdamMagaluk** [comment]
@wooliet Would you want to include that one small change in event_socket then i'd be happy to get this PR merged in.

**Comment by wooliet** [comment]
I'm sorry @AdamMagaluk , I missed this.

What specific changes would you like for me to add? Those you linked to in _lib/event_socket.js_?

**Comment by AdamMagaluk** [comment]
@wooliet Would be the changes in evet_socket from this branch. https://github.com/zettajs/zetta/commit/6206dc5ab199e0b9b039e1deac3074ee2f88db99

**Comment by AdamMagaluk** [comment]
+1

**Comment by mdobson** [comment]
+1

**Comment by AdamMagaluk** [comment]
Closing but opened new PR with commits and tests. https://github.com/zettajs/zetta/pull/317

**Pull request closed without merging**
