### PR TITLE
Presence

### PR DESCRIPTION
**Pull request by mdobson**
Features added:

- Device deletion from a driver
- Device deletion over HTTP API
- Devices in Zetta apps are notified if they are deleted or not. 

Other:

- Tests added for features
- Refactored some things around in lib/runtime.js to make it easier to test

### CODE REVIEW

**Comment by mdobson** [comment]
This will fail until the PR is updated with the new zetta-device release.

**Comment by mdobson** [comment]
Ready for review.

**Comment by AdamMagaluk** [comment]
Should we list an action on the device representation for deleting the device?

**Comment by mdobson** [comment]
I don't think so. I think adding a rel to self indicating the resource
could be deleted may be a better approach. We already do that with PUT and
the edit rel.

-Matt

**Comment by AdamMagaluk** [comment]
Is there an equivalent link relation for delete?

**Comment by AdamMagaluk** [comment]
Nevermind, edit resource implies it can also be deleted.

**Comment by mdobson** [comment]
Couldn't find one after an IANA perusal.

**Comment by mdobson** [comment]
Lucky us!

**Comment by kevinswiber** [comment]
If we allow DELETE on devices via the API, we'll need to expose an onRemoteRemove hook on the Device class.

**Comment by mdobson** [comment]
Agreed. I'll work through that today.

**Comment by AdamMagaluk** [comment]
Another thing we have to watch out for is when devices use an old version of zetta-device. Isn't exactly this PR's issue but noticed it when trying to run a test with zetta-led-mock-driver and DELETE throws:

```
/Users/ApigeeCorporation/Software/zetta/zetta/lib/runtime.js:324
  device._sendLogStreamEvent('zetta-device-destroy', [], function() {
...
```

Note sure if we can do anything to minimize this issue, maybe have zetta look at each device driver's zetta-device version and determine if it supports that version.

**Comment by mdobson** [comment]
I can put in a guard in the delete process to prevent this crash from
happening. I also feel like this may be one of those pre-1.0.0
compatibility issues too where it is solved by saying "You should
upgrade!".

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by AdamMagaluk** [comment]
When a device is deleted I would expect that transitions should no longer work for that device, or is that something a device driver has to implement.

Here's my test case:

```js
var zetta = require('zetta');
var LED = require('zetta-led-mock-driver');

zetta()
  .use(LED)
  .use(function(server) {
    var q = server.where({ type: 'led' })
    server.observe(q, function(device) {
      console.log('got device')
      device.on('logs', console.log);

      var state = 'turn-on';
      setInterval(function() {
        device.call(state);
        state = (state === 'turn-off') ? 'turn-on' : 'turn-off';
      }, 2000);
    });
  })
  .listen(3000);
```

Then at some point delete the device through the API.

**Comment by mdobson** [comment]
Going to work on tests. However I did make a few worthwhile changes to note.

- Added support for remoteDestroy hook. 
```javascript
config
  .remoteDestroy(function(cb) {
    //do some driver cleanup.
    this.connection.close(function(err) {
      if(err) {
        cb(err); //Send error
      } else if(device.readyForDestroy) {
        cb(null, true); //device will be destroyed
      } else {
        cb(null, false); //device will not be destroyed.
      }
    });
  })
```
- Made destroy() function async. An optional callback will can be provided to be fired when device is knocked out of the zetta runtime.

**Comment by mdobson** [comment]
Need two other PRs approved and published for tests to pass on this one.

**Comment by kevinswiber** [comment]
I think there's always potential for a race condition in this model.  If Peer A with Device A is linked to Peer B, an app on Peer B is waiting on a timer to complete before sending a transition request to Device A, and Device A is destroyed, Peer B will potentially remove Device A from its local _jsDevices, but the reference will still be around in the timer.

In this case, should we detect if the last state was `zetta-device-destroy` and handle the error appropriately?

**Comment by kevinswiber** [comment]
Oh, I see.  This should kick in:  https://github.com/zettajs/zetta/blob/e392b7d42e6fec3565cfbe6a44ae534ac7ab05c0/lib/virtual_device.js#L105

It would alert the caller that the transition is not available.  Is there anything more we should do in this special case?

**Comment by mdobson** [comment]
I typically would recommend that folks listen for the destroy event as
well, and null the reference appropriately if that makes sense.

```
var zetta = require('zetta');
var DeviceRegistry = require('./mem_device_registry');
var PeerRegistry = require('./mem_peer_registry');
var ChatDevice = require('./chat_device');
var Photocell = require('zetta-photocell-mock-driver');
var LED = require('./led');

zetta({registry: new DeviceRegistry(), peerRegistry: new PeerRegistry()})
  .name('hub2')
  .use(LED)
  .use(function(server) {
    var q = server.where({ type: 'led' });
    server.observe(q, function(device) {
      console.log('got device');
      device.on('logs', console.log);
      //Listen for destroy
      device.on('destroy', function() {
        device = null;
      });

      var state = 'turn-on';
      setInterval(function() {
        //Make sure device is still good to go.
        if(device) {
          device.call(state);
        }
        state = (state === 'turn-off') ? 'turn-on' : 'turn-off';
      }, 2000);
    });
  })
  .listen(1338);
```



*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by kevinswiber** [comment]
That's a good way to handle it.

My question is about when the guard _doesn't_ happen.  Is it sufficient enough to say "Transition not available?"  If the error said, "Device has been destroyed." or something to that effect, it could prompt a driver author to handle the scenario as you recommended.

**Comment by mdobson** [comment]
Good point. I'll look at the necessary changes in zetta-device to see how
that would look.

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by mdobson** [comment]
- Added tests to account for special error that occurs when transitions are called on destroyed device.

**Comment by mdobson** [comment]
zetta-device will emit the proper errors now.

**Comment by AdamMagaluk** [comment]
I say merge away.

**Pull request merged**
