### PR TITLE
Changing HTTP server to a SPDY server.

### PR DESCRIPTION
**Pull request by kevinswiber**
Just setting this here for now.

### CODE REVIEW

**Comment by kevinswiber** [comment]
Test client:

```javascript
var spdy = require('spdy');
var http = require('http');

var agent = spdy.createAgent({
  host: 'localhost',
  port: 1337,
  spdy: {
    plain: true,
    ssl: false
  }
});

var subscribe = function(topic) {
  var body = new Buffer('topic=' + topic);
  var req = http.request({
    method: 'POST',
    host: 'localhost',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Content-Length': body.length
    },
    port: 1337,
    agent: agent,
    path: '/_pubsub/subscribe'
  }, function(response) {
    if (response.statusCode === 200) {
      console.log('subscribed:', topic);
    } else {
      console.log('error:', topic);
    }
  });

  req.end(body);
};

subscribe('heartbeat/c4c4a38f-3163-45e1-98ae-d142cc1f2d87/pulse');
subscribe('led/78e63cbf-a08b-4521-a2c6-270635e73f2f/state');

agent.on('push', function(stream) {
  stream.on('data', function(data) {
    console.log(data.toString());
  });
});
```

**Comment by mdobson** [comment]
X-Signed-Off-By: @mdobson when tests pass.

**Comment by kevinswiber** [comment]
@mdobson Per our offline discussion, check the URLs in the SPDY responses now.  They should be fixed.  All tests are passing locally.  Please verify.

**Comment by kevinswiber** [comment]
Looks like there's one test failing on 0.10.x:

```
  290 passing (11s)
  1 failing

  1) Event Websocket Proxied Through Peer Receive json messages websocket should recv only one set of messages when reconnecting:
     Uncaught Error: Should have only recieved one message. 0
      at null._onTimeout (/Users/kevin/projects/zetta/test/test_event_ws_proxied.js:150:21)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by kevinswiber** [comment]
Something's going on with Virtual Devices.  The tests fail... sometimes.  Will look into it.

**Comment by kevinswiber** [comment]
Fixed VirtualDevice test.

**Comment by kevinswiber** [comment]
Last build passed.  Just squashed commits and re-pushed.  Once this bad boy passes, ready for a final review and merge.  @mdobson

**Comment by mdobson** [comment]
Quick! Just merge it now! Before another build failure.



*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by AdamMagaluk** [comment]
Working great. Tested on Windows 7 also passed with v0.10.x and v0.12.x

**Comment by mdobson** [comment]
Cool. Going to merge this in. It's been working on my SDK branch all morning.

**Pull request merged**
