### PR TITLE
Added failing test with a fix to initialize device properties when .use(...

### PR DESCRIPTION
**Pull request by AdamMagaluk**
...Device) is called

### CODE REVIEW

**Comment by anil614sagar** [comment]
Hi Adam,

I have tested above fix and found out that monitors are not getting updated once the transition happens in zetta browser. I need to refresh browser manually to see changes.

You can reproduce issue by using below code

var zetta = require('zetta');
var car = require('zetta-car-mock-driver');

zetta()
  .name('Zetta-Explorer')
  .use(car)
  .listen('1337', function() {
    console.log('zetta server is running on localhost port 1337 ');
  });

Go to zetta browser and change the state of the car to Start Car -> Accelerate Car . Speed monitor value doesn't change. On browser manual refresh we can see changes.

Cheers,
Anil Sagar

**Comment by AdamMagaluk** [comment]
Thanks Anil, will look into this today.

**Comment by AdamMagaluk** [comment]
@anil614sagar  Was able to reproduce this. This is caused when a device is provisioned from the registry, so after the first time zetta was run. There were some conflicts on how the id was set after a init function is called on the .device.

**Comment by mdobson** [comment]
+1

**Pull request merged**
