### PR TITLE
:sparkles: Add Babel boilerplate

### PR DESCRIPTION
**Pull request by marvinroger**
Run `npm run build` to generate ES5 code in the `dist` folder. This is this folder that will need to be published to NPM.

### CODE REVIEW

**Comment by marvinroger** [comment]
Not ready to merge yet. Some tests still fail, I think it's because of the way JSON is handled.

**Comment by marvinroger** [comment]
Well, I am stuck. `JSON.parse` and `JSON.stringify` reacts weirdly.

**Comment by marvinroger** [comment]
Okay, the problem happens here: https://github.com/zettajs/zetta/blob/efe177664d0021661da2e5272bf7a1bf92bcc69f/lib/event_socket.js#L226

On the non-Babel compiled version, `data = JSON.stringify(data);` actually stringify `arguments[1]`, whereas it does not on the compiled version. I don't know what's the issue, though, probably scoping or something.

**Comment by marvinroger** [comment]
Fixed! 😪 

 Some `var` were missing, some mocks contained a bug (PeerRegistry returning a string instead of an object like the actual PeerRegistry does), and there were some lucky `arguments` manipulation.

Anyway, it's working now. Here's how it works:

* There's a new `TARGET_NODE_VERSION` env variable in the Travis file. This variable contains the node version that is compatible with the codebase without transpilation.
  * If the `TARGET_NODE_VERSION` == the current tested node version, then we test the code without the transpilation
  * For every version (including the `TARGET_NODE_VERSION` as the transpiled version is the one published to NPM anyway), test the code against the transpilation

This ensures that we can develop and test on modern Node.js versions (>= TARGET_NODE_VERSION) without transpilation, and it also ensures that the built version (published to NPM) is compatible with all versions down to `0.10`. And the circle is complete. 😄

**Comment by kevinswiber** [comment]
Hey @marvinroger, this has been merged to an es2015 branch: https://github.com/zettajs/zetta/tree/es2015.

**Pull request closed without merging**
